apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
